### ISSUE TITLE
Sponsors Section

### ISSUE THREAD

**Issue by ctsstc** [BendJS/simple-website#2]
It would be nice to highlight sponsors who keep fueling Bend JS meetups.

As we become able to accept larger donations maybe there could be different levels of sponsorship?

## Acceptance Criteria
- Display sponsor:
  - Logo
  - Name
- Link to sponsor's site

**Comment by chriscoyier** [comment]
Seems like a good idea to me.

Sounds like @kcloud99 has taken steps to make BendJS a business and all that, so I imagine the first order of business after someone writes a check is to honor them with a little spot on the website.

**Comment by kcloud99** [comment]
Need to do this

**Comment by kcloud99** [comment]
First sponsors are Uptech Studio, Cloud99 Consulting, Codepen.io, Ladd Group Real Estate

**Comment by nslee333** [comment]
Closing this issue, the redesigned website has a sponsors section front and center.

**Comment by ctsstc** [comment]
Thanks @nslee333 looks great!
